// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjcbqO6Es5O4bzJfV85LeQgY1MyQtwY0s',
    appId: '1:675326316148:web:a04738b3a1e7a8e14dcb21',
    messagingSenderId: '675326316148',
    projectId: 'ezrent-8ccb2',
    authDomain: 'ezrent-8ccb2.firebaseapp.com',
    storageBucket: 'ezrent-8ccb2.firebasestorage.app',
    measurementId: 'G-VZ76F1HV6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC92Zt5CHagEtF8TnFVGbyTXDhw9BPz_AM',
    appId: '1:675326316148:android:4a1615f767daf12f4dcb21',
    messagingSenderId: '675326316148',
    projectId: 'ezrent-8ccb2',
    storageBucket: 'ezrent-8ccb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ502qrRLiB8tLQ_A_r_LL90wd_Wq409k',
    appId: '1:675326316148:ios:65db0331663180e24dcb21',
    messagingSenderId: '675326316148',
    projectId: 'ezrent-8ccb2',
    storageBucket: 'ezrent-8ccb2.firebasestorage.app',
    iosBundleId: 'com.example.ezrent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ502qrRLiB8tLQ_A_r_LL90wd_Wq409k',
    appId: '1:675326316148:ios:65db0331663180e24dcb21',
    messagingSenderId: '675326316148',
    projectId: 'ezrent-8ccb2',
    storageBucket: 'ezrent-8ccb2.firebasestorage.app',
    iosBundleId: 'com.example.ezrent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjcbqO6Es5O4bzJfV85LeQgY1MyQtwY0s',
    appId: '1:675326316148:web:287156b24bb3ee9e4dcb21',
    messagingSenderId: '675326316148',
    projectId: 'ezrent-8ccb2',
    authDomain: 'ezrent-8ccb2.firebaseapp.com',
    storageBucket: 'ezrent-8ccb2.firebasestorage.app',
    measurementId: 'G-RJZYJ1TZ38',
  );
}
